### ISSUE TITLE
RSRV : Determine what should be returned to the RSRV

### ISSUE THREAD

**Issue by gamab** [gamab/INSA_BE_QoS#2]
In my opinion the signals are OK(flow1,flow2) or NOK(flow1,flow2)
Maybe create the class associated to those signals

**Comment by idrissLaouali** [comment]
Yes, we can create File containing Global messages that will be send through the network then we can begin our part
.

**Comment by gamab** [comment]
Aren't we using GSON?

**Comment by idrissLaouali** [comment]
I  had never used it but i can learn. however, i think that the others are going to use serialization.

**Comment by gamab** [comment]
One of our teacher just hates serialization . And if we use GSON we will be able to actually see the flow description using wireshark, this will make debugging easier

**Comment by gamab** [comment]
Moreover GSON is as easy as serialization

**Comment by idrissLaouali** [comment]
Ok lets try it
